document.write('<script src="js/jquery-1.11.0.js" type="text/javascript"></script>')
document.write('<script type="text/javascript" src="js/addons/jquery.include.js"></script>')
document.write('<meta http-equiv="X-UA-Compatible" content="IE=edge">')
document.write('<meta name="viewport" content="width=device-width, initial-scale=1">')
document.write('<meta name="description" content="">')
document.write('<meta name="author" content="Tany">')
// document.write('<!-- Bootstrap Core CSS -->')
document.write('<link href="css/bootstrap.min.css" rel="stylesheet">')
// document.write('<!-- MetisMenu CSS -->')
document.write('<link href="css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">')
// document.write('<!-- Timeline CSS -->')
document.write('<link href="css/plugins/timeline.css" rel="stylesheet">')
// document.write('<!-- Custom CSS -->')
document.write('<link href="css/sb-admin-2.css" rel="stylesheet">')
// document.write('<!-- Morris Charts CSS -->')
document.write('<link href="css/plugins/morris.css" rel="stylesheet">')
// document.write('<!-- Custom Fonts -->')
document.write('<link href="font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">')
document.write('<!--[if lt IE 9]>')
document.write('<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>')
document.write('<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>')
document.write('<![endif]-->')
